dependencies:
  - smartcontractkit/chainlink@2.7.0

compiler:
  evm_version: null
  solc:
    version: v0.8.22
    remappings:
      - "@chainlink=smartcontractkit/chainlink@2.7.0"

networks:
  default: development
  mainnet-fork:
    eth_usd_priceFeed: 0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419
  Sepolia:
    eth_usd_priceFeed: 0x694AA1769357215DE4FAC081bf1f309aDC325306
    vrfCoordinator: 0x8103B0A8A00be2DDC778e6e7eaa21791Cd364625
    keyHash: 0x474e34a077df58807dbe9c96d3c009b23b3c6d0cce433e59bbf5b34f823bc56c
    link_token_contract: 0x779877A7B0D9E8603169DdbD7836e478b4624789
    verify: True
  ganache-local:
    verify: False

dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}